"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("pulpo", {
  authStatus: () => ipcRenderer.invoke("auth:status"),
  getConfig: () => ipcRenderer.invoke("config:get"),
  setConfig: (partial) => ipcRenderer.invoke("config:set", partial),
  suggestRepos: () => ipcRenderer.invoke("repos:suggest"),
  listPRs: (repo, states) => ipcRenderer.invoke("prs:list", { repo, states }),
  searchPRs: (repos, states) => ipcRenderer.invoke("prs:search", { repos, states }),
  prDetail: (repo, number) => ipcRenderer.invoke("pr:detail", { repo, number }),
  mergePR: (args) => ipcRenderer.invoke("pr:merge", args),
  updateBranch: (nodeId) => ipcRenderer.invoke("pr:updateBranch", { nodeId }),
  prFiles: (repo, number) => ipcRenderer.invoke("pr:files", { repo, number }),
  prConversation: (repo, number) => ipcRenderer.invoke("pr:conversation", { repo, number }),
  commentIssue: (repo, number, body) => ipcRenderer.invoke("pr:commentIssue", { repo, number, body }),
  commentInline: (repo, number, comment) => ipcRenderer.invoke("pr:commentInline", { repo, number, comment }),
  replyThread: (repo, number, commentDatabaseId, body) =>
    ipcRenderer.invoke("pr:replyThread", { repo, number, commentDatabaseId, body }),
  resolveThread: (threadId, resolved) => ipcRenderer.invoke("pr:resolveThread", { threadId, resolved }),
  submitReview: (repo, number, review) => ipcRenderer.invoke("pr:submitReview", { repo, number, review }),
  dismissReview: (repo, number, reviewId, message) =>
    ipcRenderer.invoke("pr:dismissReview", { repo, number, reviewId, message }),
  aiReview: (title, body, files) => ipcRenderer.invoke("ai:review", { title, body, files }),
  aiStatus: () => ipcRenderer.invoke("ai:status"),
  aiPing: () => ipcRenderer.invoke("ai:ping"),
  draftsList: (key) => ipcRenderer.invoke("drafts:list", { key }),
  draftsSave: (key, items) => ipcRenderer.invoke("drafts:save", { key, items }),
  draftsKeys: () => ipcRenderer.invoke("drafts:keys"),
  defaultBranch: (repo) => ipcRenderer.invoke("history:branches", { repo }),
  historyGraph: (repo, branchSpecs) => ipcRenderer.invoke("history:graph", { repo, branchSpecs }),
  createBranch: (repo, branch, sha) => ipcRenderer.invoke("git:createBranch", { repo, branch, sha }),
  forceUpdateBranch: (repo, branch, sha) => ipcRenderer.invoke("git:forceUpdate", { repo, branch, sha }),
  cherryPick: (repo, sha, branch, dryRun) => ipcRenderer.invoke("pr:cherryPick", { repo, sha, branch, dryRun }),
  revertPR: (repo, number) => ipcRenderer.invoke("pr:revert", { repo, number }),
  setPrDraft: (nodeId, toDraft) => ipcRenderer.invoke("pr:setDraft", { nodeId, toDraft }),
  listMilestones: () => ipcRenderer.invoke("milestones:list"),
  milestoneIssues: (title, includeClosed) => ipcRenderer.invoke("milestones:issues", { title, includeClosed }),
  groupLabels: () => ipcRenderer.invoke("issues:groupLabels"),
  updateIssue: (projectId, iid, patch) => ipcRenderer.invoke("issues:update", { projectId, iid, patch }),
  openExternal: (url) => ipcRenderer.invoke("shell:open", url),
  notify: (title, body) => ipcRenderer.invoke("notify", { title, body }),
  dockBadge: (text) => ipcRenderer.invoke("dock:badge", text),
  selftestRenderComplete: () => ipcRenderer.send("selftest:render-complete"),
});
